apiVersion: v1
kind: Secret
metadata:
  name: journey-secrets
  labels:
    app: journey
type: Opaque
stringData:
  AUTH_DATABASE_URL: {{ .Values.secrets.authDatabaseUrl | quote }}
  USER_DATABASE_URL: {{ .Values.secrets.userDatabaseUrl | quote }}
  NOTIFICATION_DATABASE_URL: {{ .Values.secrets.notificationDatabaseUrl | quote }}
  CHAT_DATABASE_URL: {{ .Values.secrets.chatDatabaseUrl | quote }}
  VEHICLE_DATABASE_URL: {{ .Values.secrets.vehicleDatabaseUrl | quote }}
  BOOKING_DATABASE_URL: {{ .Values.secrets.bookingDatabaseUrl | quote }}
  PAYMENT_DATABASE_URL: {{ .Values.secrets.paymentDatabaseUrl | quote }}
  BLOG_DATABASE_URL: {{ .Values.secrets.blogDatabaseUrl | quote }}
  RENTAL_DATABASE_URL: {{ .Values.secrets.rentalDatabaseUrl | quote }}
  REVIEW_DATABASE_URL: {{ .Values.secrets.reviewDatabaseUrl | quote }}
  DEVICE_DATABASE_URL: {{ .Values.secrets.deviceDatabaseUrl | quote }}
  ACCESS_TOKEN_SECRET: {{ .Values.secrets.accessTokenSecret | quote }}
  REFRESH_TOKEN_SECRET: {{ .Values.secrets.refreshTokenSecret | quote }}
  RESEND_API_KEY: {{ .Values.secrets.resendApiKey | quote }}
  PAYMENT_API_KEY: {{ .Values.secrets.paymentApiKey | quote }}
  REDIS_URL: {{ .Values.secrets.redisUrl | quote }}
  DIGITAL_OCEAN_SPACES_KEY: {{ .Values.secrets.digitalOceanSpacesKey | quote }}
  DIGITAL_OCEAN_SPACES_SECRET: {{ .Values.secrets.digitalOceanSpacesSecret | quote }}
  DIGITAL_OCEAN_SPACES_REGION: {{ .Values.secrets.digitalOceanSpacesRegion | quote }}
  DIGITAL_OCEAN_SPACES_END_POINT: {{ .Values.secrets.digitalOceanSpacesEndPoint | quote }}
  USER_GRPC_SERVICE_URL_NET: {{ .Values.secrets.userGrpcServiceUrlNet | quote }}
  VEHICLE_GRPC_SERVICE_URL_NET: {{ .Values.secrets.vehicleGrpcServiceUrlNet | quote }}
  DEVICE_GRPC_SERVICE_URL_NET: {{ .Values.secrets.deviceGrpcServiceUrlNet | quote }}
  RENTAL_GRPC_SERVICE_URL_NET: {{ .Values.secrets.rentalGrpcServiceUrlNet | quote }}
  BOOKING_GRPC_SERVICE_URL_NET: {{ .Values.secrets.bookingGrpcServiceUrlNet | quote }}
  PAYMENT_GRPC_SERVICE_URL_NET: {{ .Values.secrets.paymentGrpcServiceUrlNet | quote }}
