global:
  imagePullPolicy: Always

nats:
  config:
    cluster:
      enabled: false
    jetstream:
      enabled: true
      fileStorage:
        enabled: true
        dir: /data
        pvc:
          enabled: true
          size: 10Gi
          storageClassName: do-block-storage-retain
  container:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

api:
  enabled: true
  replicas: 1
  image: 'caophi562005/journey-api:latest'
  port:
    http: 3000

admin:
  enabled: true
  replicas: 1
  image: 'caophi562005/journey-admin:latest'
  port:
    http: 3100

auth:
  enabled: true
  replicas: 1
  image: 'caophi562005/journey-auth:latest'
  port:
    grpc: 5000

user:
  enabled: true
  replicas: 1
  image: 'caophi562005/journey-user:latest'
  port:
    grpc: 5001
    http: 3001

notification:
  enabled: true
  replicas: 1
  image: 'caophi562005/journey-notification:latest'
  port:
    grpc: 5002
    http: 3002

chat:
  enabled: true
  replicas: 1
  image: 'caophi562005/journey-chat:latest'
  port:
    grpc: 5003
    http: 3003

vehicle:
  enabled: true
  replicas: 1
  image: 'caophi562005/journey-vehicle:latest'
  port:
    grpc: 5004
    http: 3004

blog:
  enabled: true
  replicas: 1
  image: 'caophi562005/journey-blog:latest'
  port:
    grpc: 5005
    http: 3005

device:
  enabled: true
  replicas: 1
  image: 'caophi562005/journey-device:latest'
  port:
    grpc: 5006
    http: 3006

rental:
  enabled: true
  replicas: 1
  image: 'caophi562005/journey-rental:latest'
  port:
    grpc: 5007
    http: 3007

booking:
  enabled: true
  replicas: 1
  image: 'caophi562005/journey-booking:latest'
  port:
    grpc: 5008
    http: 3008

payment:
  enabled: true
  replicas: 1
  image: 'caophi562005/journey-payment:latest'
  port:
    grpc: 5009
    http: 3009

review:
  enabled: true
  replicas: 1
  image: 'caophi562005/journey-review:latest'
  port:
    grpc: 5010
    http: 3010

# Configuration (non-sensitive)
config:
  natsUrl: ''
  authUrl: ''
  userUrl: ''
  notificationUrl: ''
  chatUrl: ''
  vehicleUrl: ''
  blogUrl: ''
  deviceUrl: ''
  rentalUrl: ''
  reviewUrl: ''
  bookingUrl: ''
  paymentUrl: ''
  accessTokenExpiresIn: '1h'
  refreshTokenExpiresIn: '7d'
  otpExpires: '5m'
  bookingCollateral: ''
  bookingDeposit: ''
  bookingVat: ''
  bookingInsuranceFee: ''
  userGrpcServiceUrlNet: ''
  vehicleGrpcServiceUrlNet: ''
  deviceGrpcServiceUrlNet: ''
  rentalGrpcServiceUrlNet: ''
  bookingGrpcServiceUrlNet: ''
  paymentGrpcServiceUrlNet: ''

# Secrets (sensitive - DO NOT COMMIT REAL VALUES)
secrets:
  authDatabaseUrl: ''
  userDatabaseUrl: ''
  notificationDatabaseUrl: ''
  chatDatabaseUrl: ''
  vehicleDatabaseUrl: ''
  accessTokenSecret: ''
  bookingDatabaseUrl: ''
  paymentDatabaseUrl: ''
  blogDatabaseUrl: ''
  rentalDatabaseUrl: ''
  reviewDatabaseUrl: ''
  deviceDatabaseUrl: ''
  refreshTokenSecret: ''
  resendApiKey: ''
  paymentApiKey: ''
  redisUrl: ''
  digitalOceanSpacesKey: ''
  digitalOceanSpacesSecret: ''
  digitalOceanSpacesRegion: ''
  digitalOceanSpacesEndPoint: ''

# Ingress configuration
ingress:
  enabled: true
  api:
    host: 'journey-api.hacmieu.xyz'
  admin:
    host: 'journey-admin.hacmieu.xyz'
  email: 'caophi565caophi@gmail.com'
